version: "3.8"
services:
    # imagem micro 01
    app:
        build: 
            args: 
                user: thiel-serra
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: micro01_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - microservices
    
    # nginx
    nginx:
        image: nginx:alpine
        container_name: micro01_nginx
        restart: unless-stopped
        ports: 
            - 8000:80
            - 443:443
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - microservices

    # mysql micro 01
    mysql:
        image: mysql:5.7.22
        container_name: micro01_mysql
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3315:3306
        networks: 
            - microservices

    # queue micro 01
    queue:
        build: 
            args: 
                user: thiel-serra
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: micro01_queue
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - microservices

    #redis micro 01
    redis:
        image: redis:latest
        container_name: micro01_redis
        networks: 
            - microservices

networks: 
    microservices:
        driver: bridge